version: '3.4'

services:
  tiendaservicios.api.autor:
    image: tiendaserviciosapiautor:dev
    container_name: TiendaServicios.Api.Autor
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "TiendaServicios.Api.Autor"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages
    volumes:
      - C:\Users\buli\OneDrive - ERNI Group\Desktop\ERNIRepo\Microservicios con ASPNET Core, Docker y RabbitMQ\TiendaServicios\TiendaServicios.Api.Autor:/app
      - C:\Users\buli\OneDrive - ERNI Group\Desktop\ERNIRepo\Microservicios con ASPNET Core, Docker y RabbitMQ\TiendaServicios:/src
      - C:\Users\buli\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\buli\.nuget\packages\:/root/.nuget/packages:ro
      - C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages:/root/.nuget/fallbackpackages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  \"/app/bin/Debug/netcoreapp3.1/TiendaServicios.Api.Autor.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  tiendaservicios.api.carritocompra:
    image: tiendaserviciosapicarritocompra:dev
    container_name: TiendaServicios.Api.CarritoCompra
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "TiendaServicios.Api.CarritoCompra"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages
    volumes:
      - C:\Users\buli\OneDrive - ERNI Group\Desktop\ERNIRepo\Microservicios con ASPNET Core, Docker y RabbitMQ\TiendaServicios\TiendaServicios.Api.CarritoCompra:/app
      - C:\Users\buli\OneDrive - ERNI Group\Desktop\ERNIRepo\Microservicios con ASPNET Core, Docker y RabbitMQ\TiendaServicios:/src
      - C:\Users\buli\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\buli\.nuget\packages\:/root/.nuget/packages:ro
      - C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages:/root/.nuget/fallbackpackages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  \"/app/bin/Debug/net6.0/TiendaServicios.Api.CarritoCompra.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  tiendaservicios.api.gateway:
    image: tiendaserviciosapigateway:dev
    container_name: TiendaServicios.Api.Gateway
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "TiendaServicios.Api.Gateway"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages
    volumes:
      - C:\Users\buli\OneDrive - ERNI Group\Desktop\ERNIRepo\Microservicios con ASPNET Core, Docker y RabbitMQ\TiendaServicios\TiendaServicios.Api.Gateway:/app
      - C:\Users\buli\OneDrive - ERNI Group\Desktop\ERNIRepo\Microservicios con ASPNET Core, Docker y RabbitMQ\TiendaServicios:/src
      - C:\Users\buli\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\buli\.nuget\packages\:/root/.nuget/packages:ro
      - C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages:/root/.nuget/fallbackpackages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  \"/app/bin/Debug/net6.0/TiendaServicios.Api.Gateway.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  tiendaservicios.api.libro:
    image: tiendaserviciosapilibro:dev
    container_name: TiendaServicios.Api.Libro
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "TiendaServicios.Api.Libro"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages
    volumes:
      - C:\Users\buli\OneDrive - ERNI Group\Desktop\ERNIRepo\Microservicios con ASPNET Core, Docker y RabbitMQ\TiendaServicios\TiendaServicios.Api.Libro:/app
      - C:\Users\buli\OneDrive - ERNI Group\Desktop\ERNIRepo\Microservicios con ASPNET Core, Docker y RabbitMQ\TiendaServicios:/src
      - C:\Users\buli\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\buli\.nuget\packages\:/root/.nuget/packages:ro
      - C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages:/root/.nuget/fallbackpackages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  \"/app/bin/Debug/netcoreapp3.1/TiendaServicios.Api.Libro.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
